scoreboard players tag @s add 别看我只是一只羊
execute @s ~ ~ ~ scoreboard objectives add 别看我只是一只羊 dummy
execute @s ~ ~ ~ gamerule gameLoopFunction music:别看我只是一只羊
title @a actionbar "\u00a76\u00a7l播放音乐 \u00a7b\u00a7l>>\u00a7a\u00a7l别看我只是一只羊\u00a7b\u00a7l<<\u00a7r"
scoreboard players add @a[tag=别看我只是一只羊] 别看我只是一只羊 1
execute @a[score_别看我只是一只羊_min=15,score_别看我只是一只羊=15] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=20,score_别看我只是一只羊=20] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=25,score_别看我只是一只羊=25] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=30,score_别看我只是一只羊=30] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=35,score_别看我只是一只羊=35] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=40,score_别看我只是一只羊=40] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=45,score_别看我只是一只羊=45] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=50,score_别看我只是一只羊=50] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_别看我只是一只羊_min=55,score_别看我只是一只羊=55] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=75,score_别看我只是一只羊=75] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=80,score_别看我只是一只羊=80] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=85,score_别看我只是一只羊=85] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=90,score_别看我只是一只羊=90] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=95,score_别看我只是一只羊=95] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=100,score_别看我只是一只羊=100] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=105,score_别看我只是一只羊=105] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=125,score_别看我只是一只羊=125] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_别看我只是一只羊_min=130,score_别看我只是一只羊=130] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=135,score_别看我只是一只羊=135] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=145,score_别看我只是一只羊=145] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_别看我只是一只羊_min=150,score_别看我只是一只羊=150] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=155,score_别看我只是一只羊=155] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=165,score_别看我只是一只羊=165] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_别看我只是一只羊_min=170,score_别看我只是一只羊=170] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=175,score_别看我只是一只羊=175] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=180,score_别看我只是一只羊=180] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_别看我只是一只羊_min=185,score_别看我只是一只羊=185] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=190,score_别看我只是一只羊=190] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=200,score_别看我只是一只羊=200] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_别看我只是一只羊_min=205,score_别看我只是一只羊=205] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=210,score_别看我只是一只羊=210] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=220,score_别看我只是一只羊=220] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_别看我只是一只羊_min=225,score_别看我只是一只羊=225] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=230,score_别看我只是一只羊=230] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=240,score_别看我只是一只羊=240] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_别看我只是一只羊_min=245,score_别看我只是一只羊=245] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=250,score_别看我只是一只羊=250] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=255,score_别看我只是一只羊=255] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_别看我只是一只羊_min=260,score_别看我只是一只羊=260] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=265,score_别看我只是一只羊=265] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=275,score_别看我只是一只羊=275] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=280,score_别看我只是一只羊=280] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=285,score_别看我只是一只羊=285] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=290,score_别看我只是一只羊=290] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=295,score_别看我只是一只羊=295] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=300,score_别看我只是一只羊=300] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=305,score_别看我只是一只羊=305] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_别看我只是一只羊_min=310,score_别看我只是一只羊=310] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=335,score_别看我只是一只羊=335] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=340,score_别看我只是一只羊=340] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=345,score_别看我只是一只羊=345] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=350,score_别看我只是一只羊=350] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=355,score_别看我只是一只羊=355] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=360,score_别看我只是一只羊=360] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=365,score_别看我只是一只羊=365] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_别看我只是一只羊_min=370,score_别看我只是一只羊=370] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=375,score_别看我只是一只羊=375] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=395,score_别看我只是一只羊=395] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=400,score_别看我只是一只羊=400] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=405,score_别看我只是一只羊=405] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=410,score_别看我只是一只羊=410] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=415,score_别看我只是一只羊=415] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=420,score_别看我只是一只羊=420] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=425,score_别看我只是一只羊=425] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=430,score_别看我只是一只羊=430] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_别看我只是一只羊_min=435,score_别看我只是一只羊=435] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=455,score_别看我只是一只羊=455] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=460,score_别看我只是一只羊=460] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=465,score_别看我只是一只羊=465] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=470,score_别看我只是一只羊=470] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=475,score_别看我只是一只羊=475] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=480,score_别看我只是一只羊=480] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=485,score_别看我只是一只羊=485] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_别看我只是一只羊_min=490,score_别看我只是一只羊=490] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=515,score_别看我只是一只羊=515] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=520,score_别看我只是一只羊=520] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=525,score_别看我只是一只羊=525] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=530,score_别看我只是一只羊=530] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=535,score_别看我只是一只羊=535] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=540,score_别看我只是一只羊=540] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=545,score_别看我只是一只羊=545] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_别看我只是一只羊_min=550,score_别看我只是一只羊=550] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=575,score_别看我只是一只羊=575] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=580,score_别看我只是一只羊=580] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=585,score_别看我只是一只羊=585] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=590,score_别看我只是一只羊=590] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=595,score_别看我只是一只羊=595] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=600,score_别看我只是一只羊=600] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=605,score_别看我只是一只羊=605] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_别看我只是一只羊_min=610,score_别看我只是一只羊=610] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=615,score_别看我只是一只羊=615] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=635,score_别看我只是一只羊=635] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=640,score_别看我只是一只羊=640] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=645,score_别看我只是一只羊=645] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=650,score_别看我只是一只羊=650] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=655,score_别看我只是一只羊=655] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=660,score_别看我只是一只羊=660] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=665,score_别看我只是一只羊=665] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=670,score_别看我只是一只羊=670] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_别看我只是一只羊_min=675,score_别看我只是一只羊=675] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=695,score_别看我只是一只羊=695] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=700,score_别看我只是一只羊=700] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=705,score_别看我只是一只羊=705] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=710,score_别看我只是一只羊=710] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_别看我只是一只羊_min=715,score_别看我只是一只羊=715] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=720,score_别看我只是一只羊=720] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=725,score_别看我只是一只羊=725] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=735,score_别看我只是一只羊=735] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=740,score_别看我只是一只羊=740] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=745,score_别看我只是一只羊=745] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=750,score_别看我只是一只羊=750] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=755,score_别看我只是一只羊=755] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=760,score_别看我只是一只羊=760] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=765,score_别看我只是一只羊=765] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=770,score_别看我只是一只羊=770] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=775,score_别看我只是一只羊=775] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=780,score_别看我只是一只羊=780] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=785,score_别看我只是一只羊=785] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=790,score_别看我只是一只羊=790] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=795,score_别看我只是一只羊=795] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=800,score_别看我只是一只羊=800] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=805,score_别看我只是一只羊=805] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=810,score_别看我只是一只羊=810] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=815,score_别看我只是一只羊=815] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=820,score_别看我只是一只羊=820] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=825,score_别看我只是一只羊=825] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=830,score_别看我只是一只羊=830] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=835,score_别看我只是一只羊=835] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=840,score_别看我只是一只羊=840] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=845,score_别看我只是一只羊=845] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=850,score_别看我只是一只羊=850] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=855,score_别看我只是一只羊=855] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=860,score_别看我只是一只羊=860] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=865,score_别看我只是一只羊=865] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=870,score_别看我只是一只羊=870] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=875,score_别看我只是一只羊=875] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=880,score_别看我只是一只羊=880] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=885,score_别看我只是一只羊=885] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=890,score_别看我只是一只羊=890] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_别看我只是一只羊_min=895,score_别看我只是一只羊=895] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_别看我只是一只羊_min=900,score_别看我只是一只羊=900] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=905,score_别看我只是一只羊=905] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=910,score_别看我只是一只羊=910] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_别看我只是一只羊_min=915,score_别看我只是一只羊=915] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_别看我只是一只羊_min=920,score_别看我只是一只羊=920] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=925,score_别看我只是一只羊=925] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=930,score_别看我只是一只羊=930] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=935,score_别看我只是一只羊=935] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=940,score_别看我只是一只羊=940] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=945,score_别看我只是一只羊=945] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=950,score_别看我只是一只羊=950] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=970,score_别看我只是一只羊=970] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=975,score_别看我只是一只羊=975] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=990,score_别看我只是一只羊=990] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=995,score_别看我只是一只羊=995] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=1000,score_别看我只是一只羊=1000] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=1005,score_别看我只是一只羊=1005] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1010,score_别看我只是一只羊=1010] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1015,score_别看我只是一只羊=1015] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=1020,score_别看我只是一只羊=1020] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=1025,score_别看我只是一只羊=1025] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1030,score_别看我只是一只羊=1030] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1035,score_别看我只是一只羊=1035] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=1040,score_别看我只是一只羊=1040] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=1045,score_别看我只是一只羊=1045] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1050,score_别看我只是一只羊=1050] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1055,score_别看我只是一只羊=1055] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_别看我只是一只羊_min=1060,score_别看我只是一只羊=1060] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1065,score_别看我只是一只羊=1065] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1070,score_别看我只是一只羊=1070] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=1075,score_别看我只是一只羊=1075] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=1080,score_别看我只是一只羊=1080] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1085,score_别看我只是一只羊=1085] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1090,score_别看我只是一只羊=1090] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=1095,score_别看我只是一只羊=1095] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=1100,score_别看我只是一只羊=1100] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1105,score_别看我只是一只羊=1105] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1110,score_别看我只是一只羊=1110] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=1115,score_别看我只是一只羊=1115] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=1120,score_别看我只是一只羊=1120] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1125,score_别看我只是一只羊=1125] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1130,score_别看我只是一只羊=1130] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=1135,score_别看我只是一只羊=1135] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=1140,score_别看我只是一只羊=1140] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1145,score_别看我只是一只羊=1145] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_别看我只是一只羊_min=1150,score_别看我只是一只羊=1150] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_别看我只是一只羊_min=1155,score_别看我只是一只羊=1155] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1160,score_别看我只是一只羊=1160] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1165,score_别看我只是一只羊=1165] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_别看我只是一只羊_min=1170,score_别看我只是一只羊=1170] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_别看我只是一只羊_min=1175,score_别看我只是一只羊=1175] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1180,score_别看我只是一只羊=1180] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1185,score_别看我只是一只羊=1185] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=1190,score_别看我只是一只羊=1190] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=1195,score_别看我只是一只羊=1195] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=1200,score_别看我只是一只羊=1200] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=1205,score_别看我只是一只羊=1205] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=1235,score_别看我只是一只羊=1235] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.888
execute @a[score_别看我只是一只羊_min=1240,score_别看我只是一只羊=1240] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_别看我只是一只羊_min=1245,score_别看我只是一只羊=1245] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1250,score_别看我只是一只羊=1250] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_别看我只是一只羊_min=1255,score_别看我只是一只羊=1255] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_别看我只是一只羊_min=1260,score_别看我只是一只羊=1260] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_别看我只是一只羊_min=1285,score_别看我只是一只羊=1285] ~ ~ ~ gamerule gameLoopFunction -
execute @a[score_别看我只是一只羊_min=1285,score_别看我只是一只羊=1285] ~ ~ ~ scoreboard objectives remove 别看我只是一只羊
execute @a[score_别看我只是一只羊_min=1285,score_别看我只是一只羊=1285] ~ ~ ~ scoreboard players tag @s remove 别看我只是一只羊