scoreboard players tag @s add 这世界那么多人
execute @s ~ ~ ~ scoreboard objectives add 这世界那么多人 dummy
execute @s ~ ~ ~ gamerule gameLoopFunction music:这世界那么多人
title @a actionbar [{"text":"\u00a76\u00a7l播放音乐 \u00a7b\u00a7l>>\u00a7a\u00a7l这世界那么多人"},{"text":"\u00a7a\u00a7l("},{"score":{"name":"这世界那么多人","objective":"这世界那么多人","color":"green","bold":true}},{"text":"\u00a7a\u00a7l/"},{"text":"\u00a7a\u00a7l1430"},{"text":"\u00a7a\u00a7l)"},{"text":"\u00a7b\u00a7l<<\u00a7r"}]
scoreboard players add @a[tag=这世界那么多人] 这世界那么多人 1
scoreboard players add 这世界那么多人 这世界那么多人 1
execute @a[score_这世界那么多人_min=15,score_这世界那么多人=15] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_这世界那么多人_min=20,score_这世界那么多人=20] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=25,score_这世界那么多人=25] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=30,score_这世界那么多人=30] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=35,score_这世界那么多人=35] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=40,score_这世界那么多人=40] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=45,score_这世界那么多人=45] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=50,score_这世界那么多人=50] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=65,score_这世界那么多人=65] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=70,score_这世界那么多人=70] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=75,score_这世界那么多人=75] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=85,score_这世界那么多人=85] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=90,score_这世界那么多人=90] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=95,score_这世界那么多人=95] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=100,score_这世界那么多人=100] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=105,score_这世界那么多人=105] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=120,score_这世界那么多人=120] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_这世界那么多人_min=125,score_这世界那么多人=125] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=130,score_这世界那么多人=130] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=135,score_这世界那么多人=135] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=140,score_这世界那么多人=140] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=145,score_这世界那么多人=145] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=150,score_这世界那么多人=150] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=155,score_这世界那么多人=155] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_这世界那么多人_min=165,score_这世界那么多人=165] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=170,score_这世界那么多人=170] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=175,score_这世界那么多人=175] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=180,score_这世界那么多人=180] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=190,score_这世界那么多人=190] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=195,score_这世界那么多人=195] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_这世界那么多人_min=200,score_这世界那么多人=200] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=205,score_这世界那么多人=205] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=225,score_这世界那么多人=225] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_这世界那么多人_min=230,score_这世界那么多人=230] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=235,score_这世界那么多人=235] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=240,score_这世界那么多人=240] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=245,score_这世界那么多人=245] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=250,score_这世界那么多人=250] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=255,score_这世界那么多人=255] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=260,score_这世界那么多人=260] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=275,score_这世界那么多人=275] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=280,score_这世界那么多人=280] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=285,score_这世界那么多人=285] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=295,score_这世界那么多人=295] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=300,score_这世界那么多人=300] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=305,score_这世界那么多人=305] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=310,score_这世界那么多人=310] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=315,score_这世界那么多人=315] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_这世界那么多人_min=335,score_这世界那么多人=335] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_这世界那么多人_min=340,score_这世界那么多人=340] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=345,score_这世界那么多人=345] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=350,score_这世界那么多人=350] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=355,score_这世界那么多人=355] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=360,score_这世界那么多人=360] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=365,score_这世界那么多人=365] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=370,score_这世界那么多人=370] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_这世界那么多人_min=375,score_这世界那么多人=375] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=380,score_这世界那么多人=380] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=385,score_这世界那么多人=385] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=390,score_这世界那么多人=390] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=400,score_这世界那么多人=400] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=405,score_这世界那么多人=405] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_这世界那么多人_min=410,score_这世界那么多人=410] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_这世界那么多人_min=415,score_这世界那么多人=415] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=420,score_这世界那么多人=420] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=440,score_这世界那么多人=440] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=450,score_这世界那么多人=450] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=455,score_这世界那么多人=455] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=460,score_这世界那么多人=460] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=465,score_这世界那么多人=465] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=470,score_这世界那么多人=470] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=475,score_这世界那么多人=475] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=480,score_这世界那么多人=480] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=490,score_这世界那么多人=490] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_这世界那么多人_min=495,score_这世界那么多人=495] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_这世界那么多人_min=500,score_这世界那么多人=500] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_这世界那么多人_min=505,score_这世界那么多人=505] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=510,score_这世界那么多人=510] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=515,score_这世界那么多人=515] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=520,score_这世界那么多人=520] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=525,score_这世界那么多人=525] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=530,score_这世界那么多人=530] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=535,score_这世界那么多人=535] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=540,score_这世界那么多人=540] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=545,score_这世界那么多人=545] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=550,score_这世界那么多人=550] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=555,score_这世界那么多人=555] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=560,score_这世界那么多人=560] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=570,score_这世界那么多人=570] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=575,score_这世界那么多人=575] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_这世界那么多人_min=580,score_这世界那么多人=580] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_这世界那么多人_min=585,score_这世界那么多人=585] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_这世界那么多人_min=590,score_这世界那么多人=590] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=595,score_这世界那么多人=595] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=600,score_这世界那么多人=600] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=605,score_这世界那么多人=605] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=615,score_这世界那么多人=615] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=620,score_这世界那么多人=620] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=625,score_这世界那么多人=625] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=630,score_这世界那么多人=630] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_这世界那么多人_min=635,score_这世界那么多人=635] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=655,score_这世界那么多人=655] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=660,score_这世界那么多人=660] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=665,score_这世界那么多人=665] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_这世界那么多人_min=670,score_这世界那么多人=670] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_这世界那么多人_min=675,score_这世界那么多人=675] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_这世界那么多人_min=680,score_这世界那么多人=680] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=685,score_这世界那么多人=685] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=690,score_这世界那么多人=690] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_这世界那么多人_min=695,score_这世界那么多人=695] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_这世界那么多人_min=700,score_这世界那么多人=700] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=710,score_这世界那么多人=710] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_这世界那么多人_min=715,score_这世界那么多人=715] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=720,score_这世界那么多人=720] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=725,score_这世界那么多人=725] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=730,score_这世界那么多人=730] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=735,score_这世界那么多人=735] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=740,score_这世界那么多人=740] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=745,score_这世界那么多人=745] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=750,score_这世界那么多人=750] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=755,score_这世界那么多人=755] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=765,score_这世界那么多人=765] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=770,score_这世界那么多人=770] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=775,score_这世界那么多人=775] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_这世界那么多人_min=780,score_这世界那么多人=780] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_这世界那么多人_min=785,score_这世界那么多人=785] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_这世界那么多人_min=790,score_这世界那么多人=790] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=795,score_这世界那么多人=795] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=800,score_这世界那么多人=800] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_这世界那么多人_min=805,score_这世界那么多人=805] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_这世界那么多人_min=810,score_这世界那么多人=810] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_这世界那么多人_min=820,score_这世界那么多人=820] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=825,score_这世界那么多人=825] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_这世界那么多人_min=830,score_这世界那么多人=830] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_这世界那么多人_min=835,score_这世界那么多人=835] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=840,score_这世界那么多人=840] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=845,score_这世界那么多人=845] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=850,score_这世界那么多人=850] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=855,score_这世界那么多人=855] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=860,score_这世界那么多人=860] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=865,score_这世界那么多人=865] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=870,score_这世界那么多人=870] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=880,score_这世界那么多人=880] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=885,score_这世界那么多人=885] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=910,score_这世界那么多人=910] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=915,score_这世界那么多人=915] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=920,score_这世界那么多人=920] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=925,score_这世界那么多人=925] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=935,score_这世界那么多人=935] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_这世界那么多人_min=940,score_这世界那么多人=940] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=945,score_这世界那么多人=945] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=950,score_这世界那么多人=950] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_这世界那么多人_min=955,score_这世界那么多人=955] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_这世界那么多人_min=960,score_这世界那么多人=960] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_这世界那么多人_min=965,score_这世界那么多人=965] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=970,score_这世界那么多人=970] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=975,score_这世界那么多人=975] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_这世界那么多人_min=980,score_这世界那么多人=980] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_这世界那么多人_min=985,score_这世界那么多人=985] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=995,score_这世界那么多人=995] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_这世界那么多人_min=1000,score_这世界那么多人=1000] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=1005,score_这世界那么多人=1005] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=1010,score_这世界那么多人=1010] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=1015,score_这世界那么多人=1015] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1020,score_这世界那么多人=1020] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=1025,score_这世界那么多人=1025] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1030,score_这世界那么多人=1030] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=1035,score_这世界那么多人=1035] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=1045,score_这世界那么多人=1045] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=1055,score_这世界那么多人=1055] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=1060,score_这世界那么多人=1060] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=1065,score_这世界那么多人=1065] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_这世界那么多人_min=1070,score_这世界那么多人=1070] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_这世界那么多人_min=1075,score_这世界那么多人=1075] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.782
execute @a[score_这世界那么多人_min=1080,score_这世界那么多人=1080] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1085,score_这世界那么多人=1085] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=1090,score_这世界那么多人=1090] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_这世界那么多人_min=1095,score_这世界那么多人=1095] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.587
execute @a[score_这世界那么多人_min=1100,score_这世界那么多人=1100] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_这世界那么多人_min=1115,score_这世界那么多人=1115] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_这世界那么多人_min=1120,score_这世界那么多人=1120] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_这世界那么多人_min=1125,score_这世界那么多人=1125] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=1130,score_这世界那么多人=1130] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=1135,score_这世界那么多人=1135] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=1140,score_这世界那么多人=1140] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1145,score_这世界那么多人=1145] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=1150,score_这世界那么多人=1150] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1155,score_这世界那么多人=1155] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=1160,score_这世界那么多人=1160] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=1165,score_这世界那么多人=1165] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=1175,score_这世界那么多人=1175] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1180,score_这世界那么多人=1180] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1215,score_这世界那么多人=1215] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_这世界那么多人_min=1220,score_这世界那么多人=1220] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1225,score_这世界那么多人=1225] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1230,score_这世界那么多人=1230] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1235,score_这世界那么多人=1235] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=1240,score_这世界那么多人=1240] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=1245,score_这世界那么多人=1245] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=1250,score_这世界那么多人=1250] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=1265,score_这世界那么多人=1265] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=1270,score_这世界那么多人=1270] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=1275,score_这世界那么多人=1275] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1285,score_这世界那么多人=1285] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=1290,score_这世界那么多人=1290] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1295,score_这世界那么多人=1295] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=1300,score_这世界那么多人=1300] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1305,score_这世界那么多人=1305] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_这世界那么多人_min=1325,score_这世界那么多人=1325] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_这世界那么多人_min=1330,score_这世界那么多人=1330] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1335,score_这世界那么多人=1335] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1340,score_这世界那么多人=1340] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1345,score_这世界那么多人=1345] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1350,score_这世界那么多人=1350] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=1355,score_这世界那么多人=1355] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=1360,score_这世界那么多人=1360] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=1365,score_这世界那么多人=1365] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_这世界那么多人_min=1375,score_这世界那么多人=1375] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=1380,score_这世界那么多人=1380] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_这世界那么多人_min=1385,score_这世界那么多人=1385] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_这世界那么多人_min=1390,score_这世界那么多人=1390] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=1395,score_这世界那么多人=1395] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1405,score_这世界那么多人=1405] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.595
execute @a[score_这世界那么多人_min=1410,score_这世界那么多人=1410] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_这世界那么多人_min=1415,score_这世界那么多人=1415] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_这世界那么多人_min=1420,score_这世界那么多人=1420] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_这世界那么多人_min=1425,score_这世界那么多人=1425] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_这世界那么多人_min=1430,score_这世界那么多人=1430] ~ ~ ~ gamerule gameLoopFunction -
execute @a[score_这世界那么多人_min=1430,score_这世界那么多人=1430] ~ ~ ~ scoreboard objectives remove 这世界那么多人
execute @a[score_这世界那么多人_min=1430,score_这世界那么多人=1430] ~ ~ ~ scoreboard players tag @s remove 这世界那么多人