scoreboard players tag @s add 终会与你同行
execute @s ~ ~ ~ scoreboard objectives add 终会与你同行 dummy
execute @s ~ ~ ~ gamerule gameLoopFunction music:终会与你同行
title @a actionbar [{"text":"\u00a76\u00a7l播放音乐 \u00a7b\u00a7l>>\u00a7a\u00a7l终会与你同行"},{"text":"\u00a7a\u00a7l("},{"score":{"name":"终会与你同行","objective":"终会与你同行","color":"green","bold":true}},{"text":"\u00a7a\u00a7l/"},{"text":"\u00a7a\u00a7l10665"},{"text":"\u00a7a\u00a7l)"},{"text":"\u00a7b\u00a7l<<\u00a7r"}]
scoreboard players add @a[tag=终会与你同行] 终会与你同行 1
execute @a[score_终会与你同行_min=10,score_终会与你同行=10] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=20,score_终会与你同行=20] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=25,score_终会与你同行=25] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=30,score_终会与你同行=30] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=40,score_终会与你同行=40] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=45,score_终会与你同行=45] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=50,score_终会与你同行=50] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_终会与你同行_min=60,score_终会与你同行=60] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_终会与你同行_min=65,score_终会与你同行=65] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_终会与你同行_min=75,score_终会与你同行=75] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=80,score_终会与你同行=80] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=90,score_终会与你同行=90] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=95,score_终会与你同行=95] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=100,score_终会与你同行=100] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=110,score_终会与你同行=110] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=115,score_终会与你同行=115] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=125,score_终会与你同行=125] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=130,score_终会与你同行=130] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=140,score_终会与你同行=140] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=145,score_终会与你同行=145] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=150,score_终会与你同行=150] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_终会与你同行_min=160,score_终会与你同行=160] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_终会与你同行_min=165,score_终会与你同行=165] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_终会与你同行_min=170,score_终会与你同行=170] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=180,score_终会与你同行=180] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=185,score_终会与你同行=185] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=190,score_终会与你同行=190] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=200,score_终会与你同行=200] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=205,score_终会与你同行=205] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=210,score_终会与你同行=210] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=215,score_终会与你同行=215] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=220,score_终会与你同行=220] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=225,score_终会与你同行=225] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=230,score_终会与你同行=230] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=240,score_终会与你同行=240] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.530
execute @a[score_终会与你同行_min=245,score_终会与你同行=245] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_终会与你同行_min=255,score_终会与你同行=255] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_终会与你同行_min=260,score_终会与你同行=260] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_终会与你同行_min=265,score_终会与你同行=265] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_终会与你同行_min=270,score_终会与你同行=270] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=280,score_终会与你同行=280] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=285,score_终会与你同行=285] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=290,score_终会与你同行=290] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_终会与你同行_min=295,score_终会与你同行=295] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=300,score_终会与你同行=300] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=310,score_终会与你同行=310] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=315,score_终会与你同行=315] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=320,score_终会与你同行=320] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=325,score_终会与你同行=325] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=330,score_终会与你同行=330] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=335,score_终会与你同行=335] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=340,score_终会与你同行=340] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=350,score_终会与你同行=350] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_终会与你同行_min=355,score_终会与你同行=355] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_终会与你同行_min=365,score_终会与你同行=365] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_终会与你同行_min=370,score_终会与你同行=370] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_终会与你同行_min=375,score_终会与你同行=375] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.944
execute @a[score_终会与你同行_min=380,score_终会与你同行=380] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=390,score_终会与你同行=390] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=395,score_终会与你同行=395] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=400,score_终会与你同行=400] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_终会与你同行_min=405,score_终会与你同行=405] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=410,score_终会与你同行=410] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=420,score_终会与你同行=420] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_终会与你同行_min=425,score_终会与你同行=425] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_终会与你同行_min=430,score_终会与你同行=430] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=435,score_终会与你同行=435] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=445,score_终会与你同行=445] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_终会与你同行_min=450,score_终会与你同行=450] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_终会与你同行_min=455,score_终会与你同行=455] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_终会与你同行_min=460,score_终会与你同行=460] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_终会与你同行_min=465,score_终会与你同行=465] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_终会与你同行_min=475,score_终会与你同行=475] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_终会与你同行_min=480,score_终会与你同行=480] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_终会与你同行_min=485,score_终会与你同行=485] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=490,score_终会与你同行=490] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=500,score_终会与你同行=500] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_终会与你同行_min=505,score_终会与你同行=505] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_终会与你同行_min=515,score_终会与你同行=515] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_终会与你同行_min=520,score_终会与你同行=520] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=525,score_终会与你同行=525] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_终会与你同行_min=535,score_终会与你同行=535] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=540,score_终会与你同行=540] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=550,score_终会与你同行=550] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_终会与你同行_min=555,score_终会与你同行=555] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_终会与你同行_min=565,score_终会与你同行=565] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_终会与你同行_min=570,score_终会与你同行=570] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_终会与你同行_min=575,score_终会与你同行=575] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_终会与你同行_min=580,score_终会与你同行=580] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_终会与你同行_min=585,score_终会与你同行=585] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.794
execute @a[score_终会与你同行_min=590,score_终会与你同行=590] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=595,score_终会与你同行=595] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.891
execute @a[score_终会与你同行_min=600,score_终会与你同行=600] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_终会与你同行_min=605,score_终会与你同行=605] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_终会与你同行_min=610,score_终会与你同行=610] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.414
execute @a[score_终会与你同行_min=620,score_终会与你同行=620] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_终会与你同行_min=625,score_终会与你同行=625] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.335
execute @a[score_终会与你同行_min=630,score_终会与你同行=630] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_终会与你同行_min=635,score_终会与你同行=635] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_终会与你同行_min=640,score_终会与你同行=640] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_终会与你同行_min=645,score_终会与你同行=645] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_终会与你同行_min=650,score_终会与你同行=650] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.189
execute @a[score_终会与你同行_min=660,score_终会与你同行=660] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_终会与你同行_min=665,score_终会与你同行=665] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 1.059
execute @a[score_终会与你同行_min=670,score_终会与你同行=670] ~ ~ ~ playsound minecraft:block.note.harp music @a ~ ~ ~ 9 0.707
execute @a[score_终会与你同行_min=675,score_终会与你同行=675] ~ ~ ~ gamerule gameLoopFunction -
execute @a[score_终会与你同行_min=675,score_终会与你同行=675] ~ ~ ~ scoreboard objectives remove 终会与你同行
execute @a[score_终会与你同行_min=675,score_终会与你同行=675] ~ ~ ~ scoreboard players tag @s remove 终会与你同行